apiVersion: 'external-secrets.io/v1beta1'
kind: SecretStore
metadata:
  name: sb-osc-secret
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: sb-osc-external-secrets
            namespace: {{ .Release.Namespace }}
---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: sb-osc-secret
spec:
  secretStoreRef:
    name: sb-osc-secret
    kind: SecretStore
  target:
    name: sb-osc-secret
    template:
      engineVersion: v2
      data:
        secret.json: |
          {{ printf `{
            {{- $first := true }}
            {{- range $k, $v := . }}
            {{- if $first }}
              {{- $first = false }}
            {{- else }}
              {{- "," -}}
            {{- end }}
            "{{ $k }}": "{{ $v }}"
            {{- end }}
          }` }}
        redis.conf: {{ printf `| 
          requirepass {{ .redis_password }}
          appendonly yes
          save ""
          `}}
  dataFrom:
  - extract:
      key: {{ .Values.secretName }}
  refreshInterval: 10m
