apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sb-osc-access"
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.sboscRoleArn }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sb-osc-external-secrets"
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.externalsecretsRoleArn }}
